# Generated by Django 4.1.3 on 2022-11-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='captial',
            new_name='capital',
        ),
    ]
